### PR TITLE
Update installation Doc to explain to add edge repository before install

### PR DESCRIPTION
**Pull request by mcarbonneaux**
Update installation Doc to explain to add edge repository before install

### CODE REVIEW

**Comment by frenck** [comment]
This documentation is not aimed at the edge repository. As a matter of fact, the edge repository is for development purposes and should not be used.

../Frenck

**Comment by mcarbonneaux** [comment]
but you have no stable version of this module... the only disponible version is edge version...

**Comment by frenck** [comment]
Correct, the add-on hasn't been released to the public yet and only exists as a development version. It isn't listed in the add-on store for that reason.

**Comment by frenck** [comment]
It isn't published. You are looking at code.

**Pull request closed without merging**
